### ISSUE TITLE
Insufficient information to correct flycheck errors

### ISSUE THREAD

**Issue by Compro-Prasad** [Wilfred/flycheck-pkg-config#2]
When I ran `M-x flycheck-pkg-config` I entered `gtk-3.0` but instead of changing the setting it instead gives me a message. And its not written in your REAME what to do with the message.
I actually thought that it could successfully remove flycheck errors(`gtk/gtk.h: No such file or directory`) but it didn't happen. What to do next?
```
flycheck-clang-include-path: (/usr/lib/glib-2.0/include /usr/include/glib-2.0 /usr/include/libpng16 /usr/include/gdk-pixbuf-2.0 /usr/include/libpng16 /usr/include/libdrm /usr/include/harfbuzz /usr/include/freetype2 /usr/lib/glib-2.0/include /usr/include/glib-2.0 /usr/include/harfbuzz /usr/include/libpng16 /usr/include/freetype2 /usr/include/pixman-1 /usr/include/cairo /usr/include/atk-1.0 /usr/include/pango-1.0 /usr/include/cairo /usr/include/gio-unix-2.0/ /usr/include/gtk-3.0 /usr/lib/dbus-1.0/include /usr/include/dbus-1.0 /usr/include/at-spi-2.0 /usr/include/at-spi2-atk/2.0 /usr/include/gtk-3.0)
```
And there are more than one include path variables(`flycheck-cppcheck-include-path`, `flycheck-gcc-include-path`) to set but it gave a message only for `flycheck-clang-include-path` even though I had a `gcc` installation on my system instead of `clang`.

**Comment by Wilfred** [comment]
It's working correctly, the message is just reporting the current value of `flycheck-include-path` after adding it.

I've tweaked the message to make this clearer.

Flycheck uses the `flycheck-clang-include-path` for checking C/C++ with the `c/c++-clang` checker. Are you using this checker?

**Comment by Compro-Prasad** [comment]
It works now. But how do I check whether flycheck is using cppcheck, clang or gcc?

**Comment by Wilfred** [comment]
`M-x flycheck-verify-setup` will show you what is enabled.
